CREATE TABLE [dbo].[Blog]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(111,1),
	BlogTitle VARCHAR(500) NOT NULL,
	AuthorId INT NOT NULL FOREIGN KEY REFERENCES dbo.Users(Id) ON DELETE CASCADE,
	BlogContent NVARCHAR NOT NULL,
	CreationDate DATE NOT NULL
)

ALTER TABLE dbo.Blog
ALTER COLUMN CreationDate DATE
