CREATE TABLE [dbo].[RoleUpdate]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(111, 1),
	PromoterId INT NOT NULL FOREIGN KEY REFERENCES dbo.Users(Id),
	PromoteeId INT NOT NULL FOREIGN KEY REFERENCES dbo.Users(Id) ON DELETE CASCADE,
	PreviousRole INT NOT NULL FOREIGN KEY REFERENCES dbo.Roles(Id),
	NewRole INT NOT NULL FOREIGN KEY REFERENCES dbo.Roles(Id),
	DateOfChange DATE NOT NULL
);