CREATE TABLE [dbo].[UserLogIn]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(111, 1),
	Username VARCHAR(30) NOT NULL,
	Password VARCHAR(MAX) NOT NULL,
	Salt VARBINARY(1000) NOT NULL,
	UserId INT NOT NULL FOREIGN KEY REFERENCES dbo.Users(Id) ON DELETE CASCADE
)
