CREATE TABLE [dbo].[Users]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(111, 1),
	Username VARCHAR(30) NOT NULL,
	FirstName VARCHAR(50) NOT NULL,
	LastName VARCHAR(50) NOT NULL,
	Role INT NOT NULL FOREIGN KEY REFERENCES dbo.Roles(Id)
)
